---
title: "intra_day_meteo"
output: html_document
date: "2023-05-01"
---

```{r setup, include=F}
knitr::opts_chunk$set(root.dir="~/tesla-stlf")
knitr::opts_knit$set(root.dir="~/tesla-stlf")
```

```{r}
source("notebooks/intra_day/Functions.R")
library(mgcv)
library(parallel)
library(ggplot2)
library(tidyverse)
```

```{r}
## Load the data
region <- "sa"

if (region == "nsw") {
    data_file <- "data/nsw/nsw_nem.csv"
    tz <- "Australia/Sydney"
    weather_file <- "data/nsw/open_meteo_syd.csv"
} else if (region == "sa") {
    data_file <- "data/sa/sa_nem.csv"
    tz <- "Australia/Adelaide"
    weather_file <- "data/sa/open_meteo_ade.csv"
}

alldata <- read.csv(data_file)[,2:3]
#alldata$ACDT <- as.POSIXct(paste(alldata$SETTLEMENTDATE, "+1000"), format="%Y/%m/%d %T %z", tz=tz)
#alldata$ACST <- alldata$ACDT - ((as.POSIXlt(alldata$ACDT)$isdst > 0)*(60*60))
alldata$UTC <- as.POSIXct(paste(alldata$SETTLEMENTDATE, "+1000"), format="%Y/%m/%d %T %z", tz='UTC')
alldata$ACDT <- as.POSIXct(alldata$UTC, tz=tz)
alldata$ACST <- alldata$ACDT - ((as.POSIXlt(alldata$ACDT)$isdst > 0)*(60*60))

alldata$ACST.lt <- as.POSIXlt(alldata$ACST)
alldata$ACDT.lt <- as.POSIXlt(alldata$ACDT)
alldata$Time <- (alldata$ACST.lt$hour * 60 + alldata$ACST.lt$min) / (60 * 24)
alldata$DSTTime <- (alldata$ACDT.lt$hour * 60 + alldata$ACDT.lt$min) / (60 * 24)
alldata$Year <- alldata$ACDT.lt$yday / 365
alldata$wday <- alldata$ACDT.lt$wday

meteo <- read.csv(weather_file, skip = 3)
meteo$Temp <- meteo$`temperature_2m...C.`
meteo$time <- as.POSIXct(meteo$time, format="%Y-%m-%dT%H:%M", tz='UTC')

alldata$key <- as.numeric(alldata$ACST)
meteo$key <- as.numeric(meteo$time)

fitdata <- merge(alldata, meteo)#, by.x = "ACST", by.y = "time")
fitdata$WtdTemp <- wtdtemp(fitdata$DSTTime, fitdata$Temp)
fitdata$Demand <- fitdata$TOTALDEMAND

fitdata
```

```{r}
plotdata = fitdata[1:200,]
matplot(plotdata[, c("ACDT",
                     "direct_normal_irradiance..W.m..", 
                     "direct_radiation..W.m..",
                     "shortwave_radiation..W.m..",
                     "diffuse_radiation..W.m..",
                     "cloudcover....")], 
    type='l')
names(fitdata)
```

```{r}
set.seed(123)

gamlwmod <- Demand ~ s(DSTTime, bs = "cc") + s(WtdTemp, bs = "tp") + 
    s(Year, bs = "tp")
rad.form <- Demand ~ s(DSTTime, bs = "cc") + s(WtdTemp, bs = "tp") + 
    s(Year, bs = "tp") + 
    s(direct_normal_irradiance..W.m.., bs="tp")
all.form <- Demand ~ s(DSTTime, bs = "cc") + s(WtdTemp, bs = "tp") + 
    s(Year, bs = "tp") + s(direct_normal_irradiance..W.m.., bs="tp") + 
    s(diffuse_radiation..W.m..) + 
    s(shortwave_radiation..W.m.., bs="tp") + 
    s(windspeed_10m..km.h., bs="tp") + 
    s(winddirection_10m....) + s(rain..mm.) + s(cloudcover....) + 
    s(relativehumidity_2m....) #+ s(direct_radiation..W.m.., bs="tp") + 
    # direct rad too highly correlated with direct normal irrad

fit.gamm <- function(start, form) {
    train <- subset(fitdata[start:(start + 365*24),], wday %in% 1:5)
    wtdyear <- gamm(form,  data = train)
    summary(wtdyear$gam)$r.sq
}

n_splits <- 20
end <- nrow(fitdata) - 365*24
start <- seq(1, end, by = as.integer(end / n_splits))
results <- data.frame(start)
results$train_begin <- fitdata[results$start, 'ACDT']
results$gamm <- unlist(mclapply(results$start, fit.gamm, form=gamlwmod, mc.cores=8))
results$gamm.rad <- unlist(mclapply(results$start, fit.gamm, form=rad.form, mc.cores=8))
results$gamm.all <- unlist(mclapply(results$start, fit.gamm, form=all.form, mc.cores=8))
```


```{r}
plt <- results |> 
    pivot_longer(cols=c("gamm", "gamm.rad", "gamm.all"), values_to = "r.sq") |>
    mutate(model = fct_reorder2(name, train_begin, r.sq))

ggplot(plt, aes(train_begin, r.sq, colour=model)) + 
    geom_line() + geom_point() +
    scale_colour_viridis_d() +
    scale_y_continuous(expand = expansion(0.1)) +
    theme_minimal() + theme(aspect.ratio=1/3)
ggsave(paste0('plots/gamm_r2_', region, '.png'), width=6, height=2)
```

