---
title: "intra_day_model"
output: html_document
date: "2023-04-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
data_path <- "../../data/intra_day/2022.csv"
df <- read.csv(data_path)
head(df)
```

Execute train/test split.

```{r}
train <- df#[!test_ind,]
#test <- df[test_ind,]
#c(dim(df), dim(train), dim(test))
```

Try fit Model 1.

```{r}
library(mgcv)

model1 <- gam(net_load ~ s(Time, bs="cc") + abs(tempc - 20) + year,
              data=train)
summary(model1)
```

```{r}
plot(model1, all.terms=T)
```

Try fit Model 2.

```{r}
model2 <- gam(net_load ~ s(DST, bs="cc") + DST:abs(tempc - 20) + year,
              data=train)
summary(model2)
```

```{r}
plot(model2, all.terms=T)
```

Try fit Model 3.

```{r}
model3 <- gam(net_load ~ s(DST, bs="cc") + s(tempc) + year,
              data=train)
summary(model3)
```

```{r}
plot(model3, all.terms=T)
```


Try fit Model 4.

```{r}
model4 <- gam(net_load ~ s(DST, bs="cc") + s(tempc*s(DST)) + year,
              data=train)
summary(model4)
```

```{r}
plot(model4)
```

Try fit Model 5.

TODO figure out how to implement these with mgcv correctly

- s(DST) as cyclic cubic regression spline
- w(DST) as piecewise continuous sinusoidal function
- h(Temp*w(DST)) as non-periodic spline
- k(Year) as non-periodic spline

```{r}
model5 <- gamm(net_load ~ s(DST, bs="cc", k=12) + s(WtdTemp, bs="tp", k=8) + s(year, bs="tp", k=7), data=train)
summary(model5$gam)
```

```{r}
plot(model5$gam, all.terms=T)
```

